### ISSUE TITLE
Locked novels 

### ISSUE THREAD

**Issue by Dukeca** [kobolabs/Kobo-Reader#44] opened 2014-02-27 19:23 UTC
All my novels on desk top are "locked"  How do I trouble shot this

**Comment by JoyFrost** [comment] 2015-04-04 01:37
I am having the same problem. My novel is locked and I can't unlock it.

**Comment by timwillhack** [comment] 2015-04-10 16:34
Are you people actually referring to this open source project?  Or are you having trouble with the official Kobo produced software?  Also please don't make a duplicate of your issue to get the attention of someone.

**Comment by JoyFrost** [comment] 2015-04-11 00:49
no chance of anyone taking notice. no one answers your questions. I'll never buy another thing from KOBO.

**Comment by vpelletier** [comment] 2015-04-11 05:43
This is place is not Kobo's customer support, as timwillhack already mentioned. Please check their website for the intended communication methods.

**Comment by JoyFrost** [comment] 2015-04-11 22:47
This is where Kobo directs us!

**Comment by KenMacD** [comment] 2015-04-12 14:02
How/Where is Kobo directing you here? Also could you or someone provide a screenshot of what you're talking about.

This is the place to come if you're looking to build an add-on to a kobo and want to know how the kernel is compiled. It's a developer resource, not a user resource.

**Comment by JoyFrost** [comment] 2015-04-12 23:13
I have no idea why this is happening. I don't know about add ons. I ordered a book, down loaded it ,read part of it, and when i went to read it again, it was locked.  Then  I attempted to contact customer support it went to github. 


     On Sunday, April 12, 2015 10:02 AM, Kenny MacDermid <notifications@github.com> wrote:
   

 How/Where is Kobo directing you here? Also could you or someone provide a screenshot of what you're talking about.This is the place to come if you're looking to build an add-on to a kobo and want to know how the kernel is compiled. It's a developer resource, not a user resource.—

**Comment by KenMacD** [comment] 2015-04-12 23:35
@JoyFrost well, it seems you're in the wrong place. I don't know how you got here, but it's unlikely you'll find answers. It's a little like you walked in to the Boeing engineering office where the design the planes to complain that the flight attendant gave you the wrong drink.

Instead please look here https://www.kobo.com/help/contact-kobo-customer-care and if you're in North America try http://kobo.frontlinesvc.com/app/ask_NA. Good luck.

**Closed** 2015-06-06 15:05 UTC
